language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
  - '4.0'
  - '4.1'
services:
  - redis-server
script: npm link && npm run travis-test
cache:
  directories:
    - node_modules
notifications:
  email: false

